### ISSUE TITLE
multiomics wellness data and parser update v1.7.2

### ISSUE THREAD

**Issue by gglusman** [biothings/pending.api#188]
- API URL: https://biothings.ncats.io/multiomics_wellness_kp
- Github URL: https://github.com/Hadlock-Lab/Multiomics_Wellness_KP
- Git branch/commit: [1585146](https://github.com/Hadlock-Lab/multiomics_wellness_kp/commit/15851467f50f0aaaee1f48e7c95b4fe204b06b7f)
- No. Documents: 679,420
- Main change: Added knowledge_level and agent_type to each edge.

**Comment by everaldorodrigo** [comment]
Hi @colleenXu @gglusman,

Do you know if the version for the next release is going to be the same as before, version 1.7? It follows these URLs:
- "https://storage.googleapis.com/multiomics_provider_kp_data/wellness/wellness_kg_edges_v1.7.tsv"
- "https://storage.googleapis.com/multiomics_provider_kp_data/wellness/wellness_kg_nodes_v1.7.tsv"

Thank you! Looking forward to your response. Best regards,
Everaldo

**Comment by gglusman** [comment]
Hmm, no, it's supposed to be 1.7.2. Where are you seeing those URLs? I may have neglected to change something.
Thanks!

**Comment by everaldorodrigo** [comment]
The URLs are the manifest.json file here:
- https://github.com/Hadlock-Lab/multiomics_wellness_kp/blob/25aa9b6d94c48eb94bb18694b7c03332e5249741/manifest.json#L10

**Comment by gglusman** [comment]
Edited!

**Comment by everaldorodrigo** [comment]
Hello @gglusman, I think we also need to change the version here:
- https://github.com/Hadlock-Lab/multiomics_wellness_kp/blob/cc3ff34d429fb655287b445c4a4e058f6485ea1e/version.py#L5

**Comment by gglusman** [comment]
Done (on main). Not sure how I feel about having the version number stated in so many different places...

**Comment by everaldorodrigo** [comment]
> Done (on main). Not sure how I feel about having the version number stated in so many different places...

Agree! We could think a way to centralize the version number.

**Comment by everaldorodrigo** [comment]
Hey @gglusman, the last changes were released to the CI environment. Let me know if the data looks good to you.

**Comment by colleenXu** [comment]
It looks like the "missing biolink prefix" on subject/object type is still happening (initially pointed out in [Translator Slack](https://ncatstranslator.slack.com/archives/C022EL8D3AB/p1713374179125949)).

**Comment by gglusman** [comment]
Indeed, sorry about that!
Had to rebuild the graph to fix. Re-uploaded to the google bucket at same location. I guess @everaldorodrigo needs to reprocess it?

**Comment by everaldorodrigo** [comment]
Hi @gglusman and @colleenXu. I just released a new version to the CI environment.

Look, the total number of documents released is 668,753. It didn't match to the 679,420 documents showed in the description. I think worth a validation.

**Comment by ctrl-schaff** [comment]
Released on all instances. Closing for now
